version: '2'
services:
  wordpress-dsignsomething:
    image: wordpress
    ports:
    - 8080:80
    links:
    - mysql:mysql
    environment:
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: dsignsomethingdev
    volumes:
    - ./src:/var/www/html
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dsignsomethingdev
      MYSQL_DATABASE: wordpress
    volumes:
    - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
